name: SportRabbit
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.0.6 <4.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  nhost_flutter_auth: ^3.0.1
  shared_preferences: ^2.2.0
  webview_flutter: ^4.4.2
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# flutter: null
#  assets:
#     - web/icons/Icon-192.png
uses-material-design: true
